// OpenAPI-SHA256: 0626b64820eef54b850b8a60b43df0566789a8b0abea679ea635646d194b9981
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted alerts and detections */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an alert */
        get: operations["alert_detail_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the bounded SOC assistant */
        post: operations["assistant_chat_api_v1_assistant_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attack/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence-backed ATT&CK mappings */
        get: operations["attack_mappings_api_v1_attack_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List read-only audit records */
        get: operations["audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted correlation executions */
        get: operations["correlation_executions_api_v1_correlation_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explicitly run the existing Phase 5 correlation service */
        post: operations["run_correlation_api_v1_correlation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent bounded SOC activity */
        get: operations["dashboard_activity_api_v1_dashboard_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read exact SOC dashboard counts */
        get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read bounded alert and incident trends */
        get: operations["dashboard_trends_api_v1_dashboard_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normalized events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a normalized event */
        get: operations["event_detail_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API process health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents */
        get: operations["incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get incident and bounded evidence detail */
        get: operations["incident_detail_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update analyst-owned incident fields */
        patch: operations["update_incident_api_v1_incidents__incident_id__patch"];
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the existing Phase 6 investigation workflow */
        post: operations["investigate_api_v1_incidents__incident_id__investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List investigations for an incident */
        get: operations["incident_investigations_api_v1_incidents__incident_id__investigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/response/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List response actions for an incident */
        get: operations["response_list_api_v1_incidents__incident_id__response_actions_get"];
        put?: never;
        /** Propose one evidence-bound simulation-only response action */
        post: operations["response_propose_api_v1_incidents__incident_id__response_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/response/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create deterministic simulation-only action proposals */
        post: operations["response_recommend_api_v1_incidents__incident_id__response_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent investigation runs */
        get: operations["investigations_api_v1_investigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a completed or in-progress investigation */
        get: operations["investigation_detail_api_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iocs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted indicators */
        get: operations["iocs_api_v1_iocs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iocs/{ioc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a persisted indicator */
        get: operations["ioc_detail_api_v1_iocs__ioc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check database and schema readiness */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/response/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a response action */
        get: operations["response_get_api_v1_response_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/response/actions/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending response proposal */
        post: operations["response_approve_api_v1_response_actions__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/response/actions/{action_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a simulation only */
        post: operations["response_execute_api_v1_response_actions__action_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/response/actions/{action_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending response proposal */
        post: operations["response_reject_api_v1_response_actions__action_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/response/actions/{action_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll back simulated state only */
        post: operations["response_rollback_api_v1_response_actions__action_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search incidents, alerts, and IOCs */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read authenticated system status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Health */
        get: operations["public_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Liveness */
        get: operations["public_liveness_liveness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Readiness */
        get: operations["public_readiness_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Ready */
        get: operations["public_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Version */
        get: operations["public_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Severity */
            severity?: string | null;
            /** Timestamp */
            timestamp: string;
            /** Title */
            title?: string | null;
        };
        /** AlertResponse */
        AlertResponse: {
            /** Alert Id */
            alert_id?: string | null;
            /** Attack Mappings */
            attack_mappings?: {
                [key: string]: unknown;
            }[];
            /** Confidence */
            confidence?: string | number | null;
            /** Destination Ip */
            destination_ip?: string | null;
            /** Event Type */
            event_type?: string | null;
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Evidence Refs */
            evidence_refs?: string[] | null;
            /** Explanation */
            explanation?: string | null;
            /** Hostname */
            hostname?: string | null;
            /** Incident Id */
            incident_id?: string | null;
            /** Iocs */
            iocs?: {
                [key: string]: unknown;
            }[];
            /** Mitre Technique */
            mitre_technique?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Severity */
            severity?: string | null;
            /** Source Ip */
            source_ip?: string | null;
            /** Status */
            status?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Title */
            title?: string | null;
            /** Username */
            username?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** AssistantChatRequest */
        AssistantChatRequest: {
            /** Context */
            context?: {
                [key: string]: string | number | boolean | null;
            };
            /** Question */
            question: string;
        };
        /** AssistantChatResponse */
        AssistantChatResponse: {
            /** Answer */
            answer: string;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string;
            /** Warning */
            warning?: string | null;
        };
        /** AttackMappingResponse */
        AttackMappingResponse: {
            /** Baseline Disagreement */
            baseline_disagreement?: boolean | null;
            /** Baseline Techniques */
            baseline_techniques?: string[];
            /** Confidence */
            confidence?: number | null;
            /** Detection Id */
            detection_id: string;
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Id */
            id: string;
            /** Mapping Source */
            mapping_source?: string | null;
            /** Tactic Ids */
            tactic_ids?: string[];
            /** Technique Id */
            technique_id: string;
            /** Technique Name */
            technique_name: string;
        } & {
            [key: string]: unknown;
        };
        /** AuditResponse */
        AuditResponse: {
            /** Action */
            action: string;
            /** Actor */
            actor?: string | null;
            /** Audit Id */
            audit_id?: number | null;
            /** Details */
            details?: unknown;
            /** Resource Id */
            resource_id?: string | null;
            /** Resource Type */
            resource_type: string;
            /** Timestamp */
            timestamp: string;
        } & {
            [key: string]: unknown;
        };
        /** CorrelationExecutionResponse */
        CorrelationExecutionResponse: {
            /** Candidate Count */
            candidate_count?: number | null;
            /** Completed At */
            completed_at?: string | null;
            /** Edge Count */
            edge_count?: number | null;
            /** Errors */
            errors?: unknown;
            /** Execution Id */
            execution_id: string;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** CorrelationRunResponse */
        CorrelationRunResponse: {
            /**
             * Candidate Count
             * @default 0
             */
            candidate_count: number;
            /**
             * Edge Count
             * @default 0
             */
            edge_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /** Errors */
            errors?: string[];
            /** Execution Id */
            execution_id?: string | null;
            /**
             * Incident Created
             * @default 0
             */
            incident_created: number;
            /**
             * Incident Merged
             * @default 0
             */
            incident_merged: number;
            /**
             * Incident Updated
             * @default 0
             */
            incident_updated: number;
            /**
             * Suppressed Count
             * @default 0
             */
            suppressed_count: number;
        } & {
            [key: string]: unknown;
        };
        /** DashboardActivity */
        DashboardActivity: {
            /** Items */
            items?: components["schemas"]["ActivityItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Active Incidents */
            active_incidents: number;
            /** Critical Incidents */
            critical_incidents: number;
            /** Detection Count */
            detection_count: number;
            /** High Severity Alerts */
            high_severity_alerts: number;
            /** Ioc Count */
            ioc_count: number;
            /** Recent Investigations */
            recent_investigations: number;
            /** Unresolved Alerts */
            unresolved_alerts: number;
        };
        /** DashboardTrends */
        DashboardTrends: {
            /** Alert Activity */
            alert_activity: components["schemas"]["TrendCount"][];
            /** Days */
            days: number;
            /** Incident Activity */
            incident_activity: components["schemas"]["TrendCount"][];
            /** Severity Distribution */
            severity_distribution: components["schemas"]["TrendCount"][];
            /** Top Sources */
            top_sources: {
                [key: string]: components["schemas"]["TrendSource"][];
            };
        };
        /** EventResponse */
        EventResponse: {
            /** Dst Ip */
            dst_ip?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Event Type */
            event_type?: string | null;
            /** Host */
            host?: string | null;
            /** Id */
            id?: string | null;
            /** Raw */
            raw?: unknown;
            /** Source Type */
            source_type?: string | null;
            /** Src Ip */
            src_ip?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** User */
            user?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** IOCDetectionResponse */
        IOCDetectionResponse: {
            /** Alert Id */
            alert_id: string;
            /** Rule Id */
            rule_id?: string | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IOCEventResponse */
        IOCEventResponse: {
            /** Dst Ip */
            dst_ip?: string | null;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type?: string | null;
            /** Host */
            host?: string | null;
            /** Source Type */
            source_type?: string | null;
            /** Src Ip */
            src_ip?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** User */
            user?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IOCIncidentResponse */
        IOCIncidentResponse: {
            /** Incident Id */
            incident_id: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IOCResponse */
        IOCResponse: {
            /** Detections */
            detections?: components["schemas"]["IOCDetectionResponse"][];
            /** Events */
            events?: components["schemas"]["IOCEventResponse"][];
            /** First Seen */
            first_seen?: string | null;
            /** Incidents */
            incidents?: components["schemas"]["IOCIncidentResponse"][];
            /** Ioc Id */
            ioc_id?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Occurrence Count */
            occurrence_count?: number | null;
            /** Type */
            type?: string | null;
            /** Value */
            value?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            /** Analyst Notes */
            analyst_notes?: string | null;
            /** Attack Mappings */
            attack_mappings?: components["schemas"]["AttackMappingResponse"][];
            /** Confidence */
            confidence?: string | number | null;
            /** Correlation Edges */
            correlation_edges?: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at?: string | null;
            /** Description */
            description?: string | null;
            /** Detection Count */
            detection_count?: number | null;
            /** Detection Ids */
            detection_ids?: string[];
            /** Events */
            events?: components["schemas"]["EventResponse"][];
            /** First Seen */
            first_seen?: string | null;
            /** Incident Id */
            incident_id: string;
            /** Iocs */
            iocs?: components["schemas"]["IOCResponse"][];
            /** Last Seen */
            last_seen?: string | null;
            /** Merge History */
            merge_history?: {
                [key: string]: unknown;
            }[];
            /** Primary Host */
            primary_host?: string | null;
            /** Primary Src Ip */
            primary_src_ip?: string | null;
            /** Primary User */
            primary_user?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IncidentPatch */
        IncidentPatch: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: string | null;
        };
        /** IncidentResponse */
        IncidentResponse: {
            /** Analyst Notes */
            analyst_notes?: string | null;
            /** Confidence */
            confidence?: string | number | null;
            /** Created At */
            created_at?: string | null;
            /** Description */
            description?: string | null;
            /** Detection Count */
            detection_count?: number | null;
            /** First Seen */
            first_seen?: string | null;
            /** Incident Id */
            incident_id: string;
            /** Last Seen */
            last_seen?: string | null;
            /** Primary Host */
            primary_host?: string | null;
            /** Primary Src Ip */
            primary_src_ip?: string | null;
            /** Primary User */
            primary_user?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** InvestigateRequest */
        InvestigateRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            /** Ai Confidence */
            ai_confidence?: string | null;
            /** Ai Unavailable */
            ai_unavailable?: boolean | null;
            /** Attack Mappings */
            attack_mappings?: {
                [key: string]: unknown;
            }[];
            /** Completed At */
            completed_at?: string | null;
            /** Confidence Warning */
            confidence_warning?: boolean | null;
            /** Deterministic Confidence */
            deterministic_confidence?: string | null;
            /** Evidence Ids */
            evidence_ids?: {
                [key: string]: unknown;
            }[];
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
            /** Incident Id */
            incident_id: string;
            /** Investigation Id */
            investigation_id: string;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Recommendations */
            recommendations?: {
                [key: string]: unknown;
            }[];
            /** Run Number */
            run_number?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Items[InvestigationResponse] */
        Items_InvestigationResponse_: {
            /** Items */
            items?: components["schemas"]["InvestigationResponse"][];
            /** Total */
            total: number;
        };
        /** Page[AlertResponse] */
        Page_AlertResponse_: {
            /** Items */
            items?: components["schemas"]["AlertResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[AttackMappingResponse] */
        Page_AttackMappingResponse_: {
            /** Items */
            items?: components["schemas"]["AttackMappingResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[AuditResponse] */
        Page_AuditResponse_: {
            /** Items */
            items?: components["schemas"]["AuditResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[CorrelationExecutionResponse] */
        Page_CorrelationExecutionResponse_: {
            /** Items */
            items?: components["schemas"]["CorrelationExecutionResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[EventResponse] */
        Page_EventResponse_: {
            /** Items */
            items?: components["schemas"]["EventResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[IOCResponse] */
        Page_IOCResponse_: {
            /** Items */
            items?: components["schemas"]["IOCResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[IncidentResponse] */
        Page_IncidentResponse_: {
            /** Items */
            items?: components["schemas"]["IncidentResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[InvestigationResponse] */
        Page_InvestigationResponse_: {
            /** Items */
            items?: components["schemas"]["InvestigationResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Database */
            database: string;
            /** Schema Version */
            schema_version?: number | null;
            /** Status */
            status: string;
        };
        /** ResponseActionRequest */
        ResponseActionRequest: {
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "simulate_block_ip" | "simulate_disable_account" | "collect_evidence" | "increase_monitoring" | "create_case_note" | "mark_incident_reviewed";
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Supersedes */
            supersedes?: string | null;
            /** Target */
            target?: string | null;
            /** Target Type */
            target_type?: ("ip" | "host" | "account" | "domain") | null;
        };
        /** ResponseActionResponse */
        ResponseActionResponse: {
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /** Approval Binding Hash */
            approval_binding_hash: string;
            /** Approval Required */
            approval_required: boolean;
            /** Approval State */
            approval_state: string;
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /** Created At */
            created_at: string;
            /** Evidence */
            evidence: {
                [key: string]: string;
            }[];
            /**
             * Execution Mode
             * @constant
             */
            execution_mode: "simulation";
            /** Execution State */
            execution_state: string;
            /** Expires At */
            expires_at: string | null;
            /** Incident Id */
            incident_id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Playbook Id */
            playbook_id: string | null;
            /** Playbook Version */
            playbook_version: string | null;
            /** Policy Rule Id */
            policy_rule_id: string;
            /** Policy Version */
            policy_version: string;
            /** Requested By */
            requested_by: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Revision */
            revision: number;
            /** Supersedes */
            supersedes: string | null;
            /** Target */
            target: string | null;
            /** Target Type */
            target_type: string | null;
            /** Updated At */
            updated_at: string;
            /** Verification State */
            verification_state: string;
        };
        /** ResponseDecisionRequest */
        ResponseDecisionRequest: {
            /**
             * Expected Status
             * @constant
             */
            expected_status: "pending";
        };
        /** ResponseExecutionRequest */
        ResponseExecutionRequest: {
            /**
             * Expected Status
             * @enum {string}
             */
            expected_status: "not_started" | "rolled_back";
        };
        /** ResponseRecommendationRequest */
        ResponseRecommendationRequest: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** ResponseRejectRequest */
        ResponseRejectRequest: {
            /**
             * Expected Status
             * @constant
             */
            expected_status: "pending";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ResponseRollbackRequest */
        ResponseRollbackRequest: {
            /**
             * Expected Status
             * @constant
             */
            expected_status: "simulated";
        };
        /** SearchAlert */
        SearchAlert: {
            /** Alert Id */
            alert_id: string;
            /** Host */
            host?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** User */
            user?: string | null;
        };
        /** SearchIOC */
        SearchIOC: {
            /** First Seen */
            first_seen?: string | null;
            /** Ioc Id */
            ioc_id: string;
            /** Last Seen */
            last_seen?: string | null;
            /** Type */
            type: string;
            /** Value */
            value: string;
        };
        /** SearchIncident */
        SearchIncident: {
            /** Incident Id */
            incident_id: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Severity */
            severity?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Alerts */
            alerts: components["schemas"]["SearchAlert"][];
            /** Incidents */
            incidents: components["schemas"]["SearchIncident"][];
            /** Iocs */
            iocs: components["schemas"]["SearchIOC"][];
            /** Query */
            query: string;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Ai Provider */
            ai_provider: string;
            /** Ai Provider Status */
            ai_provider_status: string;
            /** Application Version */
            application_version: string;
            /** Database */
            database: string;
            /** Environment */
            environment: string;
            /** Schema Version */
            schema_version: number | null;
            /** Status */
            status: string;
        };
        /** TrendCount */
        TrendCount: {
            /** Count */
            count: number;
            /** Date */
            date?: string | null;
            /** Severity */
            severity?: string | null;
        };
        /** TrendSource */
        TrendSource: {
            /** Count */
            count: number;
            /** Value */
            value: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: string | null;
                status?: string | null;
                rule_id?: string | null;
                mitre_technique?: string | null;
                host?: string | null;
                user?: string | null;
                source_ip?: string | null;
                since?: string | null;
                until?: string | null;
                search?: string | null;
                sort?: "timestamp_desc" | "timestamp_asc" | "severity_desc";
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_detail_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_chat_api_v1_assistant_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attack_mappings_api_v1_attack_mappings_get: {
        parameters: {
            query?: {
                technique_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttackMappingResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_v1_audit_get: {
        parameters: {
            query?: {
                action?: string | null;
                actor?: string | null;
                resource_type?: string | null;
                resource_id?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correlation_executions_api_v1_correlation_executions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CorrelationExecutionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_correlation_api_v1_correlation_run_post: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_activity_api_v1_dashboard_activity_get: {
        parameters: {
            query?: {
                kind?: ("detection" | "incident" | "investigation") | null;
                severity?: string | null;
                since?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardActivity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_trends_api_v1_dashboard_trends_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTrends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                source_type?: string | null;
                host?: string | null;
                user?: string | null;
                src_ip?: string | null;
                dst_ip?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_detail_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity?: string | null;
                risk_level?: string | null;
                min_risk_score?: number | null;
                max_risk_score?: number | null;
                primary_host?: string | null;
                primary_user?: string | null;
                primary_src_ip?: string | null;
                confidence?: string | null;
                since?: string | null;
                until?: string | null;
                sort?: "created_desc" | "created_asc" | "risk_desc" | "risk_asc";
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IncidentResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_detail_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_incident_api_v1_incidents__incident_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_api_v1_incidents__incident_id__investigate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InvestigateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_investigations_api_v1_incidents__incident_id__investigations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_InvestigationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_list_api_v1_incidents__incident_id__response_actions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_propose_api_v1_incidents__incident_id__response_actions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_recommend_api_v1_incidents__incident_id__response_recommend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResponseRecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigations_api_v1_investigations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvestigationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_detail_api_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iocs_api_v1_iocs_get: {
        parameters: {
            query?: {
                type?: string | null;
                value?: string | null;
                first_seen?: string | null;
                last_seen?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IOCResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ioc_detail_api_v1_iocs__ioc_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ioc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IOCResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_get_api_v1_response_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_approve_api_v1_response_actions__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_execute_api_v1_response_actions__action_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_reject_api_v1_response_actions__action_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseRejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    response_rollback_api_v1_response_actions__action_id__rollback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseRollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    public_liveness_liveness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    public_readiness_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    public_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    public_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
