import { useCallback } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { useApiResource } from '../hooks/useApiResource'
import { LoadingState, ErrorState, EmptyState } from '../components/States'
import { LongText } from '../components/LongText'
import { sanitizeSecurityText, utcOrLocalTimestamp } from '../utils/security'
import { useTimeMode } from '../layouts/SocLayout'

export function InvestigationsPage() {
  const load=useCallback((signal:AbortSignal)=>api.investigations({limit:50,offset:0},signal),[]),{data,error,loading,retry}=useApiResource(load),mode=useTimeMode()
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">EVIDENCE-BOUNDED AI</p><h1>Investigation history</h1><p className="subtle-copy">AI output is advisory. Evidence references and deterministic data remain visible for analyst review.</p></div></div>
    <section className="panel table-panel"><h2>Recent investigation runs</h2>{loading?<LoadingState label="Loading investigation history…"/>:error?<ErrorState error={error} retry={retry}/>:!data?.items?.length?<EmptyState>No investigation runs are recorded.</EmptyState>:<div className="table-scroll"><table aria-label="Investigation history"><thead><tr><th>Run</th><th>Status</th><th>Provider</th><th>Model</th><th>Started</th><th>Completed</th><th>Classification</th><th>Confidence</th><th>Incident</th></tr></thead><tbody>{data.items.map((run)=><tr key={run.investigation_id}><td><Link className="table-link" to={`/investigations/${encodeURIComponent(run.investigation_id)}`}>#{run.run_number??'—'}</Link></td><td>{sanitizeSecurityText(run.status)}</td><td>{sanitizeSecurityText(run.provider||'Not available')}</td><td>{sanitizeSecurityText(run.model||'Not available')}</td><td>{utcOrLocalTimestamp(run.started_at,mode)}</td><td>{utcOrLocalTimestamp(run.completed_at,mode)}</td><td>{sanitizeSecurityText(run.classification||'Not available')}</td><td>{sanitizeSecurityText(run.ai_confidence||'Not available')}</td><td><Link className="table-link" to={`/incidents/${encodeURIComponent(run.incident_id)}`}>{sanitizeSecurityText(run.incident_id)}</Link></td></tr>)}</tbody></table></div>}</section>
  </div>
}

export function InvestigationDetailPage() {
  const {investigationId=''}=useParams(),load=useCallback((signal:AbortSignal)=>api.investigation(investigationId,signal),[investigationId]),{data,error,loading,retry}=useApiResource(load),mode=useTimeMode()
  return <div className="page-stack"><Link to="/investigations" className="back-link">← Investigation history</Link>{loading?<LoadingState label="Loading investigation result…"/>:error?<ErrorState error={error} retry={retry}/>:!data?<EmptyState>Investigation run not found.</EmptyState>:<>
    <section className="incident-hero panel"><p className="eyebrow">AI-GENERATED · ADVISORY ONLY</p><h1>Investigation run #{data.run_number??'—'}</h1><div className="incident-meta"><div><span>STATUS</span><strong>{sanitizeSecurityText(data.status)}</strong></div><div><span>PROVIDER / MODEL</span><strong>{sanitizeSecurityText(data.provider||'Unavailable')} / {sanitizeSecurityText(data.model||'Unavailable')}</strong></div><div><span>STARTED · {mode}</span><time>{utcOrLocalTimestamp(data.started_at,mode)}</time></div><div><span>COMPLETED · {mode}</span><time>{utcOrLocalTimestamp(data.completed_at,mode)}</time></div><div><span>INCIDENT</span><Link to={`/incidents/${encodeURIComponent(data.incident_id)}`} className="table-link">{sanitizeSecurityText(data.incident_id)}</Link></div></div></section>
    {['failed','invalid','stale'].includes(data.status)&&<div role="alert" className="security-warning">This investigation ended with status {sanitizeSecurityText(data.status)}. No validated AI analysis is available for this run.</div>}
    <section className="panel detail-card"><h2>Investigation summary</h2><p className="ai-output"><LongText value={data.summary} limit={2000} label="AI summary"/></p><p className="subtle-copy">AI-generated interpretation · verify against observed evidence.</p></section>
    <section className="panel detail-card"><h2>Findings</h2>{!data.findings?.length?<EmptyState>No findings were returned.</EmptyState>:<ul className="investigation-list">{data.findings.map((finding,index)=><li key={index}><LongText value={finding.text||finding.description||finding.finding||finding.title||JSON.stringify(finding)} limit={1000} label="AI finding"/><span className="confidence-chip">{sanitizeSecurityText(finding.basis||'AI-generated')} · {sanitizeSecurityText(finding.confidence||'confidence not reported')}</span></li>)}</ul>}</section>
    <section className="panel detail-card"><h2>Evidence used</h2>{!data.evidence_ids?.length?<EmptyState>No evidence references were recorded.</EmptyState>:<ul className="reference-list">{data.evidence_ids.map((item,index)=><li key={`${item.evidence_type}-${item.evidence_id}-${index}`}><span>{sanitizeSecurityText(item.evidence_type,60)}</span><span className="mono">{sanitizeSecurityText(item.evidence_id,160)}</span><span>{sanitizeSecurityText(item.relationship,120)}</span></li>)}</ul>}</section>
    <section className="panel detail-card"><h2>Recommended next steps</h2>{!data.recommendations?.length?<EmptyState>No recommendations were returned.</EmptyState>:<ul className="investigation-list">{data.recommendations.map((recommendation,index)=><li key={index}><LongText value={[recommendation.action,recommendation.reason].filter((value)=>typeof value==='string').join(' · ')||recommendation.description||recommendation.recommendation||JSON.stringify(recommendation)} limit={1000} label="AI recommendation"/><span className="confidence-chip">{sanitizeSecurityText(recommendation.priority||'Advisory')} · analyst-controlled</span></li>)}</ul>}</section>
  </>}</div>
}
